# Convolutional Neural Network (CNN)

This project will include making a handwritten digit recogniser using CNN using MNIST dataset.

First we will import our packages.

In [1]:
from PIL import Image
import mnist #for the dataset
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

We will now split the data into testing and training.

In [2]:
X_train = mnist.train_images()
X_test = mnist.test_images()
y_train = mnist.train_labels()
y_test = mnist.test_labels()

Lets observe the shape of our data including how many instances and results there are

In [3]:
print(X_train) # we can see this is a 3d array (3 square brackets)
print(f'Dimensions of input training data: {X_train.ndim}')
print(y_train) # we can see this is a 1d array (1 square bracket)
print(f'Dimensions of output training data: {y_train.ndim}')

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
Dimensions of input training data: 3
[5 0 4 ... 5 6 8]
Dimensions of output training data: 1


In [4]:
print(f'The shape of the input training data: {X_train.shape}') # 60000 instances for training (each image is 28*28 pixels)
print(f'The shape of the input testing data: {X_test.shape}')  # 10000 instances for testing
print(f'The shape of the output training data: {y_train.shape}') # 60000 results for training
print(f'The shape of the output testing data: {y_test.shape}')  # 10000 results for testing

The shape of the input training data: (60000, 28, 28)
The shape of the input testing data: (10000, 28, 28)
The shape of the output training data: (60000,)
The shape of the output testing data: (10000,)


This is what a single input might look like (which corresponds to a written number)

In [5]:
X_train[59999]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

We need to change the shape of X so it works with CNN

In [6]:
X_train = X_train.reshape(60000,28*28) 
X_test = X_test.reshape(10000,28*28)

Now lets check what a single instance looks like

In [7]:
print(X_train.shape)
X_train[59999]

(60000, 784)


array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

We see that the numbers for the pixels range from 0 to 256 but neural networks work better when the range is 1 so we will change this from 0 to 1.

In [8]:
X_train = (X_train/256)
X_test = (X_test/256)

In [9]:
print(X_train[59999]) #we now see all the pixel values are between 0 and 1

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

Model building - now we will create the CNN

The hidden layer sizes were chosen arbitrarily, we can potentially optimise the model by changing this.

In [10]:
cnn = MLPClassifier(hidden_layer_sizes = (100,100), activation = "relu", solver = "adam") 

In [11]:
cnn.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(100, 100))

Lets look at some predictions and the accuracy of the CNN

In [12]:
predicted = cnn.predict(X_test)
print(f'The CNN made these predictions: \n {predicted}')
print(f'The actual results were: \n {y_test}')

The CNN made these predictions: 
 [7 2 1 ... 4 5 6]
The actual results were: 
 [7 2 1 ... 4 5 6]


In [13]:
#to get the accuracy, we get the sum of the diagonal elements and divide by sum of all elements in the confusion matrix

matrix = confusion_matrix(predicted, y_test)

def accuracy_CNN(m):
    trace = m.trace()
    sum_of_elements = m.sum()
    return trace/sum_of_elements

print(f'The percentage accuracy of this model is {accuracy_CNN(matrix)*100} %')

The percentage accuracy of this model is 97.96000000000001 %


Lets test it with our own imported numbers which we drew.

First we import our numbers.

In [14]:
number7 = Image.open("no7.png") # data is inverted 
number7

In [15]:
number3 = Image.open("no3.png") # data is inverted 
number3

In [16]:
number2 = Image.open("no2.png") # data is inverted 
number2

In [17]:
data7 = list(number7.getdata())
data3 = list(number3.getdata())
data2 = list(number2.getdata())

Make sure values for pixels are between 0 and 1

In [18]:
for i in range(len(data7)):
    data7[i] = 256-data7[i]

for i in range(len(data3)):
    data3[i] = 256-data3[i]
    
for i in range(len(data2)):
    data2[i] = 256-data2[i]

In [19]:
data7 = np.array(data7)/256
print(f'CNN predicted {cnn.predict([data7])} while value was actually 7')

data3 = np.array(data3)/256
print(f'CNN predicted {cnn.predict([data3])} while value was actually 3')

data2 = np.array(data2)/256
print(f'CNN predicted {cnn.predict([data2])} while value was actually 2')

CNN predicted [7] while value was actually 7
CNN predicted [3] while value was actually 3
CNN predicted [2] while value was actually 2


The numbers predicted were correct!